### ISSUE TITLE
"and" & "inq" loopback filter

### ISSUE THREAD

**Issue by Biax2099** [strongloop-community/loopback-connector-elastic-search#73]
Hello, i found this comment 
`// TODO: or	Logical OR operator`
`// TODO: and Logical AND operator`
`//   {"where":{"and":[{"id":{"inq":["1","2","3","4"]}},{"vip":true}]}}`
in lib/esConnector.js.

I would ask you, if will be developed in few time and if i can help in some way.

Thank you so much!

**Comment by pulkitsinghal** [comment]
@Biax2099 - The community would certainly welcome any contributions you can make.

Usually contributors fork & clone the connector and then get used to running the tests with or without docker. Afterwards they dive into the code to get desired results and submit with a few new tests of their own, proving that the new functionality works and that nothing from the past is broken.

The submitted PR is reviewed, some changes may occur and then merge happens. Quickly thereafter a release to npmjs is performed so that the community can benefit and the contributors are given credit in the changelog.

While I or @aquid could make this change ourselves in 2-4 days. We are way too swamped with our day job to do so anytime soon.

**Comment by aquid** [comment]
Resolved...

**Comment by Biax2099** [comment]
thanks @pulkitsinghal
