### ISSUE TITLE
Incorrect usage of where filter in loopback

### ISSUE THREAD

**Issue by aquid** [strongloop-community/loopback-connector-elastic-search#79]
Loopback internally does some model calls with where filter in a wrong pattern. Ideally where filter in loopback should just have single direct property clause and if there are multiple clauses associated with different properties then they all should be inside “and/ or” filter. 
**Proof** -  I can see a query in ACL which does something like this: 
```
{ 
  Where: { 
    model: 'Category', 
    property: { inq: [ 'count', '*' ] }, 
    accessType: { inq: [ 'READ','*' ] } 
  }
}
```
While this should be written in a way like this:
```
{ 
  Where: { 
    and : [
      model: 'Category', 
      property: { inq: [ 'count', '*' ] },
      accessType: { inq: [ 'READ','*' ]}
    ] 
  }
}
```
This I guess wrong and maybe we can send a PR to loopback for this. 
cc @pulkitsinghal

**Comment by pulkitsinghal** [comment]
Not sure if it is "wrong" or just a convention in loopback ORM where they assume that if nothing is specified then siblings should be `AND`ed

cc @bajtos @aquid

**Comment by bajtos** [comment]
> assume that if nothing is specified then siblings should be treated with an AND

Yes, I believe that's the case. Looks like our test suite does not cover this important use case, would you like to contribute few new tests to fix that? Here is the source where to start: [test/basic-querying.test.js#L142](https://github.com/strongloop/loopback-datasource-juggler/blob/76c73d55d28dfa150b9e004aeae12aafe0ce6475/test/basic-querying.test.js#L142) and documentation for new contributors: http://loopback.io/doc/en/contrib/code-contrib.html Please mention my handle (`@bajtos`) in pull request description so that I can review it sooner.
